### ISSUE TITLE
start.dart - ProgressBar 기능 추가

### ISSUE THREAD

**Issue by Hwang-seo-i** [Miribyeol/MIRI-APP#15]
## 목적
> 챌린지 단계에 따라 progress 표현
## 작업 내용
- [ ] challenge_list.dart에 challengeStep 받아오기
- [ ] challenge.dart에 챌린지 완료 또는 안할래요 클릭 시 challengeStep 갱신
- [ ] start.dart에 challengeStep 받아온 후 ProgressBar 기능 추가

**Comment by jjy0921** [comment]
완료
